#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: compile OpenWrt_package_luci

on:
  push:
    branches: 
      - master
  #schedule:
  #  - cron: 0 0 1 * *
  #watch:
  #  types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: 准备工作
        uses: actions/checkout@master
#        with:
#          fetch-depth: 0

      - name: 部署编译环境
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
          rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
      - name: 下载lede源码并移动到根目录
        run: |
          git clone https://github.com/coolsnowwolf/lede
          mv ./lede/* ./
      - name: 下载其他插件源码到package
        run: |
          git clone https://github.com/kjrzxu/package.git  package/package
      - name: 升级安装feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 配置config文件
        run: |
          touch ./.config
          # 机型设置:
          cat >> .config <<EOF
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_hiwifi_hc5962=y
          # 插件
          CONFIG_PACKAGE_luci-app-cloudflared=y
          EOF
          make defconfig
      - name: 下载软件包
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
      - name: 开始编译固件
        run: |
          echo -e "$(nproc) thread build."
          make package/package/luci-app-cloudflared/compile V=99
      - name : 上传bin文件夹(固件+ipk)到 github actions
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_-package_luci
          path: bin/
